[package]
name = "blog_os"
version = "0.1.0"
authors = ["Kyle Montgomery <kmontg003@gmail.com"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"